version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  ApplicationStop:
    - location: backend/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: backend/app_start.sh
      timeout: 300
      runas: ec2-user
